export const GRAPE_VARIETIES = [
  // Reds
  'Pinot Noir',
  'Cabernet Sauvignon',
  'Merlot',
  'Syrah / Shiraz',
  'Grenache',
  'Nebbiolo',
  'Sangiovese',
  'Tempranillo',
  'Malbec',
  'Zinfandel',
  'Barbera',
  'Gamay',
  'Cabernet Franc',
  'Mourvèdre',
  'Carménère',
  // Whites
  'Chardonnay',
  'Sauvignon Blanc',
  'Riesling',
  'Pinot Grigio / Gris',
  'Chenin Blanc',
  'Viognier',
  'Gewurztraminer',
  'Albariño',
  'Vermentino',
  'Grüner Veltliner',
  'Pinot Blanc',
  'Marsanne',
  'Roussanne',
  'Verdejo',
  'Moscato',
] as const;
