export const WINE_REGIONS = [
  'Burgundy',
  'Bordeaux',
  'Champagne',
  'Rhône Valley',
  'Loire Valley',
  'Alsace',
  'Provence',
  'Languedoc-Roussillon',
  'Tuscany',
  'Piedmont',
  'Veneto',
  'Sicily',
  'Rioja',
  'Ribera del Duero',
  'Priorat',
  'Galicia',
  'Douro',
  'Alentejo',
  'Napa Valley',
  'Sonoma',
  'Willamette Valley',
  'Finger Lakes',
  'Marlborough',
  'Central Otago',
  'Barossa Valley',
  'McLaren Vale',
  'Clare Valley',
  'Mendoza',
  'Mosel',
  'Rheingau',
  'Pfalz',
  'Wachau',
] as const;
