export const WINE_REGIONS = [
  'Burgundy',
  'Bordeaux',
  'Champagne',
  'Rhone',
  'Other France',
  'Piedmont',
  'Tuscany',
  'Other Italy',
  'Rioja',
  'Other Spain',
  'Portugal',
  'Germany',
  'California',
  'Washington',
  'Oregon',
  'New Zealand',
  'Barossa Valley',
  'Other Australia',
  'Canada',
  'Chile',
  'Argentina',
] as const;
