import { forwardRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { colors } from '../constants/theme';

// Branded 4:5 portrait card (1080×1350) for sharing personality sketches.
// Rendered off-screen by the personality screen, captured to PNG with
// react-native-view-shot, and dropped into the native share sheet.

interface Props {
  title: string | null;
  body: string;
  category: 'wine' | 'recipe';
}

export const PersonalityShareCard = forwardRef<View, Props>(({ title, body, category }, ref) => {
  const heading = category === 'wine' ? 'My Wine Personality' : 'My Chef Personality';
  return (
    <View ref={ref} collapsable={false} style={styles.card}>
      <View style={styles.inner}>
        <View style={styles.topRow}>
          <Text style={styles.brand}>VINSTER</Text>
          <Text style={styles.brandTagline}>Your AI Sommelier</Text>
        </View>

        <View style={styles.divider} />

        <Text style={styles.subhead}>{heading}</Text>

        {title ? <Text style={styles.title}>{title}</Text> : null}

        <Text style={styles.body}>{body}</Text>

        <View style={styles.footer}>
          <Text style={styles.footerLine}>Generated by Vinster</Text>
          <Text style={styles.footerCta}>Find your gastronomic personality</Text>
        </View>
      </View>
    </View>
  );
});

const CARD_WIDTH = 1080;
const CARD_HEIGHT = 1350;
const PADDING = 90;

const styles = StyleSheet.create({
  card: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    backgroundColor: '#0E0E0E',
    padding: 28,
  },
  inner: {
    flex: 1,
    borderWidth: 4,
    borderColor: colors.gold,
    borderRadius: 36,
    paddingHorizontal: PADDING,
    paddingVertical: PADDING - 16,
    backgroundColor: '#141414',
    justifyContent: 'space-between',
  },
  topRow: {
    alignItems: 'center',
  },
  brand: {
    fontFamily: 'CormorantGaramond_700Bold',
    fontSize: 64,
    color: '#FFFFFF',
    letterSpacing: 12,
  },
  brandTagline: {
    fontFamily: 'CormorantGaramond_400Regular_Italic',
    fontSize: 28,
    color: 'rgba(255,255,255,0.55)',
    marginTop: 6,
    letterSpacing: 1.5,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(212,176,96,0.55)',
    marginVertical: 36,
  },
  subhead: {
    fontFamily: 'CormorantGaramond_600SemiBold',
    fontSize: 32,
    color: 'rgba(212,176,96,0.85)',
    textTransform: 'uppercase',
    letterSpacing: 6,
    textAlign: 'center',
    marginBottom: 24,
  },
  title: {
    fontFamily: 'CormorantGaramond_700Bold',
    fontSize: 80,
    color: colors.gold,
    letterSpacing: 1,
    lineHeight: 90,
    textAlign: 'center',
    marginBottom: 40,
  },
  body: {
    flex: 1,
    fontFamily: 'CormorantGaramond_400Regular',
    fontSize: 36,
    color: '#FFFFFF',
    lineHeight: 56,
  },
  footer: {
    alignItems: 'center',
    marginTop: 20,
  },
  footerLine: {
    fontFamily: 'CormorantGaramond_600SemiBold',
    fontSize: 24,
    color: colors.gold,
    letterSpacing: 4,
  },
  footerCta: {
    fontFamily: 'CormorantGaramond_400Regular_Italic',
    fontSize: 26,
    color: 'rgba(255,255,255,0.55)',
    marginTop: 6,
  },
});
