import { VINSTER_INSTALL_URL, VINSTER_TAGLINE } from '../constants/share';
import type { Pairing } from '../types/wine';

// Print/share HTML for a recipe pairing. Used to generate a readable PDF (via
// expo-print's printToFileAsync) so a shared/emailed recipe arrives as a proper
// document rather than an unreadable screenshot image.
export function buildRecipeHtml(pairing: Pairing, wineLine: string): string {
  const esc = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const ingredients = pairing.recipe.ingredients.map((i) => `<li>${esc(i)}</li>`).join('');
  const method = pairing.recipe.instructions.map((step) => `<li>${esc(step)}</li>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/>
<title>${esc(pairing.dishName)} — Vinster</title>
<style>
  body { font-family: Georgia, 'Times New Roman', serif; color: #1A1A1A; margin: 40px; line-height: 1.5; }
  .brand { text-align: center; letter-spacing: 6px; font-size: 14px; color: #8A6A1F; text-transform: uppercase; margin-bottom: 6px; }
  .brand-sub { text-align: center; font-style: italic; color: #8A6A1F; font-size: 13px; margin-bottom: 24px; }
  .to-pair { text-align: center; font-size: 13px; color: #555; text-transform: uppercase; letter-spacing: 2px; }
  .wine { text-align: center; font-size: 22px; font-weight: bold; margin: 4px 0 28px; }
  hr { border: none; border-top: 1px solid #DDD; margin: 16px 0 24px; }
  h1 { font-size: 28px; margin: 0 0 4px; font-weight: bold; }
  .chef { font-style: italic; color: #444; margin-bottom: 4px; }
  .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
  h2 { font-size: 16px; text-transform: uppercase; letter-spacing: 2px; color: #8A6A1F; margin: 24px 0 8px; }
  p, li { font-size: 14px; }
  ul, ol { padding-left: 20px; }
  ul li { margin-bottom: 4px; }
  ol li { margin-bottom: 10px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #DDD; text-align: center; font-size: 13px; color: #555; }
  .footer .get { letter-spacing: 4px; color: #8A6A1F; font-weight: bold; }
  .footer .url { color: #1A1A1A; font-weight: bold; margin-top: 4px; }
</style></head><body>
  <div class="brand">Recipe Pairing</div>
  <div class="brand-sub">Generated by Vinster</div>
  <div class="to-pair">To pair with</div>
  <div class="wine">${esc(wineLine || '')}</div>
  <hr/>
  <h1>${esc(pairing.dishName)}</h1>
  <div class="chef">Inspired by ${esc(pairing.chefInspiration)}</div>
  <div class="meta">Serves ${esc(String(pairing.recipe.servings))} · Prep ${esc(pairing.recipe.prepTime)} · Cook ${esc(pairing.recipe.cookTime)}</div>
  <h2>Pairing notes</h2>
  <p>${esc(pairing.pairingNotes)}</p>
  <h2>Introduction</h2>
  <p>${esc(pairing.introduction)}</p>
  <h2>Ingredients</h2>
  <ul>${ingredients}</ul>
  <h2>Method</h2>
  <ol>${method}</ol>
  <div class="footer">
    <div class="get">GET VINSTER</div>
    <div>${esc(VINSTER_TAGLINE)}</div>
    <div class="url">${VINSTER_INSTALL_URL.replace(/^https?:\/\//, '')}</div>
  </div>
</body></html>`;
}
