import { useEffect, useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, ActivityIndicator } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useCellar, useWishList } from '../../../src/hooks/useCellar';
import { getWineKnowledge } from '../../../src/api/label';
import type { WineKnowledgeData } from '../../../src/types/wine';
import { colors, spacing } from '../../../src/constants/theme';
import { fonts } from '../../../src/constants/fonts';

export default function WineKnowledgeScreen() {
  const { wineId } = useLocalSearchParams<{ wineId: string }>();
  const { wines, updateWine } = useCellar();
  const { wines: wishlistWines } = useWishList();
  const wine = wines.find((w) => w.id === wineId) ?? wishlistWines.find((w) => w.id === wineId);

  const [knowledge, setKnowledge] = useState<WineKnowledgeData | null>(wine?.wine_knowledge ?? null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!wine) return;
    // Use the cached profiles when present; otherwise generate once and persist
    // them onto the cellar row so reopening is instant and free.
    if (wine.wine_knowledge) {
      setKnowledge(wine.wine_knowledge);
      return;
    }
    let cancelled = false;
    (async () => {
      setLoading(true);
      setError(null);
      try {
        const data = await getWineKnowledge({
          producer: wine.producer ?? '',
          region: wine.region ?? '',
          wineName: wine.wine_name || null,
          vintage: wine.vintage || null,
          grape: wine.grape_variety || null,
        });
        if (cancelled) return;
        setKnowledge(data);
        // Best-effort cache write — failure just means we regenerate next time.
        try {
          await updateWine.mutateAsync({
            id: wine.id,
            updates: { wine_knowledge: data, wine_knowledge_at: new Date().toISOString() },
          });
        } catch { /* non-fatal */ }
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : 'Could not load wine knowledge.');
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [wine?.id]);

  // Header line — an exact replica of the wine card's header (same producer ·
  // name · region · vintage dedup, then grape underneath).
  const headerLine = (() => {
    if (!wine) return '';
    const sameName = wine.wine_name?.trim().toLowerCase() === wine.producer?.trim().toLowerCase();
    const parts = sameName
      ? [wine.producer, wine.region, wine.vintage]
      : [wine.producer, wine.wine_name, wine.region, wine.vintage];
    return parts.filter(Boolean).join(' · ');
  })();

  // Short title used in the editorial body — name + vintage.
  const wineTitle = wine ? (wine.vintage ? `${wine.vintage} ${wine.wine_name}` : wine.wine_name) : '';

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
          <Text style={styles.backText}>Back</Text>
        </TouchableOpacity>
        <View style={{ width: 44 }} />
      </View>

      {!wine ? (
        <View style={styles.empty}>
          <Text style={styles.emptyTitle}>Wine not found</Text>
          <Text style={styles.emptyBody}>Open this from the wine card to dive deeper.</Text>
        </View>
      ) : (
        <ScrollView contentContainerStyle={styles.content}>
          {/* Wine card header replica */}
          <Text style={styles.cardHeaderLine}>{headerLine}</Text>
          {wine.grape_variety ? <Text style={styles.cardGrape}>{wine.grape_variety}</Text> : null}

          {/* Branded masthead — mirrors the recipe pairing page. */}
          <Text style={styles.brandHeading}>Wine Knowledge</Text>
          <Text style={styles.brandSub}>Generated by Vinster</Text>

          <View style={styles.ruleRow}>
            <View style={styles.rule} />
            <Text style={styles.ruleMark}>◇</Text>
            <View style={styles.rule} />
          </View>

          <Text style={styles.wineHeader}>{wineTitle}</Text>
          <View style={styles.shortDivider} />

          {loading ? (
            <View style={styles.loadingBlock}>
              <ActivityIndicator color={colors.gold} />
              <Text style={styles.loadingText}>Vinster is researching this wine…</Text>
            </View>
          ) : error ? (
            <View style={styles.loadingBlock}>
              <Text style={styles.emptyBody}>{error}</Text>
            </View>
          ) : knowledge ? (
            <>
              <Text style={styles.sectionLabel}>Producer Profile</Text>
              <Text style={styles.body}>{knowledge.producerProfile}</Text>

              <Text style={styles.sectionLabel}>Region Profile</Text>
              <Text style={styles.body}>{knowledge.regionProfile}</Text>

              <Text style={styles.sectionLabel}>Vintage Profile</Text>
              <Text style={styles.body}>{knowledge.vintageProfile}</Text>

              <Text style={styles.sectionLabel}>Grape Variety</Text>
              <Text style={styles.body}>{knowledge.grapeProfile}</Text>
            </>
          ) : null}
        </ScrollView>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: { paddingTop: 70, paddingHorizontal: spacing.xl, paddingBottom: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  backText: { fontSize: 16, fontFamily: fonts.bodyRegular, color: colors.textMuted },
  content: { paddingHorizontal: spacing.xl, paddingTop: spacing.lg, paddingBottom: 80 },

  // Wine card header replica.
  cardHeaderLine: { fontSize: 22, fontFamily: fonts.bodyBold, color: colors.text, lineHeight: 28, textAlign: 'center' },
  cardGrape: { fontSize: 13, fontFamily: fonts.bodyRegular, color: colors.gold, marginTop: 2, textAlign: 'center', marginBottom: spacing.lg },

  brandHeading: { fontFamily: fonts.headingSemibold, fontSize: 14, color: colors.gold, letterSpacing: 4, textTransform: 'uppercase', textAlign: 'center' },
  brandSub: { fontFamily: fonts.headingItalic, fontSize: 14, color: 'rgba(224,184,74,0.75)', textAlign: 'center', marginTop: 4 },

  ruleRow: { flexDirection: 'row', alignItems: 'center', alignSelf: 'stretch', marginTop: spacing.md, marginBottom: spacing.md },
  rule: { flex: 1, height: 1, backgroundColor: 'rgba(224,184,74,0.45)' },
  ruleMark: { color: colors.gold, fontSize: 12, marginHorizontal: spacing.sm },

  wineHeader: { fontFamily: fonts.headingBold, fontSize: 26, color: colors.text, textAlign: 'center', lineHeight: 32 },
  shortDivider: { width: 40, height: 1, backgroundColor: 'rgba(224,184,74,0.55)', alignSelf: 'center', marginVertical: spacing.lg },

  sectionLabel: { fontFamily: fonts.bodySemibold, fontSize: 13, color: colors.gold, letterSpacing: 2.5, textTransform: 'uppercase', marginTop: spacing.lg, marginBottom: spacing.xs },
  body: { fontFamily: fonts.bodyRegular, fontSize: 16, color: colors.text, lineHeight: 24 },

  loadingBlock: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.xl },
  loadingText: { fontFamily: fonts.bodyItalic, fontSize: 14, color: colors.textMuted, textAlign: 'center' },

  empty: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: spacing.xl, gap: spacing.sm },
  emptyTitle: { fontFamily: fonts.headingBold, fontSize: 22, color: colors.text, textAlign: 'center' },
  emptyBody: { fontFamily: fonts.bodyRegular, fontSize: 15, color: colors.textMuted, textAlign: 'center', lineHeight: 22 },
});
