-- 089 — Cellar insider note ("The Inside Line")
-- Vinster's "sommelier best friend" verdict for a wine — how the vintage fared
-- and how the producer stacked up against peers. Already generated by the
-- wine-intelligence function (insiderNote) and shown on the scan Wine Intel
-- card; this persists it on the cellar row so the same line can appear on the
-- cellar wine card. Filled when a wine's intel is generated; null until then.

alter table public.cellar_wines
  add column if not exists insider_note text;

-- Reload PostgREST's schema cache so the new column is queryable immediately.
notify pgrst, 'reload schema';
